# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

sudo: true

os:
  - linux
  - osx

env:
  - FROM_PACKAGE_MANAGER= # Use the latest version from the package manager
  - LAZ_VER=1.0.14
  - LAZ_VER=1.2.6
  - LAZ_VER=1.4.4
  - LAZ_VER=1.4.4 LAZ_WINE=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
  - LAZ_VER=1.4.4 LAZ_WINE=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || true"

install:
  - ./.travis.install.py

script:
  - $LAZ_WINE lazbuild --widgetset=nogui $LAZ_OPT my_lazarus_tests.lpi
  - $LAZ_WINE ./bin/my_lazarus_tests --all --format=plain
