# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT


language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx
  - windows

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_PKG=true  # Use the latest version from the default package manager. (apt, brew or choco)
    - LAZ_VER=1.8.2 # Use specific (binary) release from SourceForce

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"
    - os: windows
      language: shell
      env: LAZ_VER=2.0.2 LAZ_REL=32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: windows
      language: shell
      env: LAZ_VER=2.0.2 LAZ_REL=64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install python3 --params "/InstallDir:C:\python3"; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=/c/Python3:/c/Python3/Scripts:/c/lazarus:$PATH; fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
    Xvfb $DISPLAY &
  fi

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python ./.travis.install.py; fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./.travis.install.py; fi

script:
  - lazbuild $LAZ_OPT my_lazarus_tests.lpi               # Build my_lazarus_test project
  - $LAZ_ENV ./bin/my_lazarus_tests --all --format=plain # Run my_lazarus_test testsuite

notifications:
  email:
    on_success: false
    on_failure: change
